### Collecting Deaths from their Lists

In [1]:
import itertools
import os
import pandas as pd
import re
import warnings

from pyvis.network import Network

warnings.filterwarnings('ignore')

In [2]:
kills = pd.DataFrame(columns=['universe', 'character', 'killed', 'victims'])
deaths = pd.DataFrame(columns=['universe', 'entry', 'character', 'responsible party', 'death', 'type'])
edges = pd.DataFrame(columns=['universe', 'killer', 'victim', 'death', 'type'])

aliases = pd.read_csv('Database/alias.tsv', sep='\t')
groups = pd.read_csv('Database/group.tsv', sep='\t')
versions = pd.read_csv('Database/version.tsv', sep='\t')
worlds = pd.read_csv('Database/world.tsv', sep='\t')

In [3]:
for path, subdirs, files in os.walk('Universes'):
	for name in files:
		if not name.endswith('.tsv'):
			continue

		file = os.path.join(path, name)
		parts = file.split('\\')

		universe = parts[1]

		world = ''
		for part in parts:
			if worlds.loc[(worlds['universe'] == universe) & (worlds['world'] == part)].any().all():
				world = part

		entry_parts = parts[2:-1] + [name.replace('.tsv', '')]
		entry = ' / '.join(entry_parts)

		tsv = pd.read_csv(file, sep='\t')

		for i in range(len(tsv)):
			character = tsv['character'][i]
			if world:
				character = f"{character} ({world})"
			killer = str(tsv['killed by'][i]).split(' | ')
			description = tsv['death'][i]
			type_var = tsv['type'][i]

			if killer == ['nan']:
				killer = []

			if world:
				killer = [f"{k} ({world})" for k in killer if k]

			for i in range(len(killer)):
				row = [universe, killer[i], 1, character]
				kills.loc[len(kills)] = row

				row = [universe, killer[i], character, description, type_var]
				edges.loc[len(edges)] = row

			if killer == []:
				row = [universe, '', character, description, type_var]
				edges.loc[len(edges)] = row

			row = [universe, entry, character, killer, description, type_var]
			deaths.loc[len(deaths)] = row

### Counting and Naming Deaths

In [4]:
def count_and_name(name):
	if isinstance(name, str):
		match = re.match(r"^<(\d+(?:[.,]\d+)*)(\+)?>\s*(.*)$", name)

		if match:
			count = int(match.group(1).replace(',', '').replace('.', ''))
			minimum = match.group(2) == '+'

			return name, count, False, minimum

		match = re.match(r"^{(\d+(?:[.,]\d+)*)(\+)?}\s*(.*)$", name)

		if match:
			count = int(match.group(1).replace(',', '').replace('.', ''))
			minimum = match.group(2) == '+'
			rename = match.group(3)

			return rename, count, True, minimum

	return name, 1, True, False

def format_count(value, minimum):
	if minimum:
		return f"{value}+"
	return str(value)

deaths[['character', 'count', 'named', 'minimum']] = deaths['character'].apply(lambda x: pd.Series(count_and_name(x)))
kills[['victims', 'killed', 'named', 'minimum']] = kills['victims'].apply(lambda x: pd.Series(count_and_name(x)))
edges[['victim', 'count', 'named', 'minimum']] = edges['victim'].apply(lambda x: pd.Series(count_and_name(x)))

### Replacing Groups with Character Names

In [5]:
remove = False

rows = []
drops = []

for i in range(len(kills)):
	universe = kills['universe'][i]
	character = kills['character'][i]
	victim = kills['victims'][i]
	pool = groups[groups['universe'] == universe]
	pool.reset_index(inplace=True)

	for j in range(len(pool)):
		if character == pool['group'][j]:
			news = str(pool['characters'][j]).split(' | ')
			for new in news:
				rows.append({
					'universe': universe,
					'character': new,
					'killed': kills.loc[i, 'killed'],
					'victims': kills.loc[i, 'victims'],
					'named': kills.loc[i, 'named'],
					'minimum': kills.loc[i, 'minimum']
				})
			drops.append(i)

		if victim == pool['group'][j]:
			news = str(pool['characters'][j]).split(' | ')
			for new in news:
				rows.append({
					'universe': universe,
					'character': kills.loc[i, 'character'],
					'killed': kills.loc[i, 'killed'],
					'victims': new,
					'named': kills.loc[i, 'named'],
					'minimum': kills.loc[i, 'minimum']
				})
			drops.append(i)

kills.drop(index=drops, inplace=True)
kills = pd.concat([kills, pd.DataFrame(rows)], ignore_index=True)


for i in range(len(deaths)):
	universe = deaths['universe'][i]
	character = deaths['character'][i]
	party = deaths['responsible party'][i]
	pool = groups[groups['universe'] == universe]
	pool.reset_index(inplace=True)

	changes = []

	for j in range(len(pool)):
		if character == pool['group'][j]:
			new = str(pool['characters'][j]).split(' | ')
			deaths.at[i, 'character'] = new

	for member in party:
		remove = False
		for j in range(len(pool)):
			if member == pool['group'][j]:
				news = str(pool['characters'][j]).split(' | ')
				changes.extend(news)
				remove = True
		if not remove:
			changes.append(member)

	deaths.at[i, 'responsible party'] = changes


rows = []
drops = []

for i in range(len(edges)):
	universe = edges['universe'][i]
	killer = edges['killer'][i]
	victim = edges['victim'][i]
	pool = groups[groups['universe'] == universe]
	pool.reset_index(inplace=True)

	for j in range(len(pool)):
		if killer == pool['group'][j]:
			news = str(pool['characters'][j]).split(' | ')
			for new in news:
				rows.append({
					'universe': universe,
					'killer': new,
					'victim': edges.loc[i, 'victim'],
					'death': edges.loc[i, 'death'],
					'type': edges.loc[i, 'type'],
					'count': edges.loc[i, 'count'],
					'named': edges.loc[i, 'named'],
					'minimum': edges.loc[i, 'minimum']
				})
			drops.append(i)

		if victim == pool['group'][j]:
			news = str(pool['characters'][j]).split(' | ')
			for new in news:
				rows.append({
					'universe': universe,
					'killer': edges.loc[i, 'killer'],
					'victim': new,
					'death': edges.loc[i, 'death'],
					'type': edges.loc[i, 'type'],
					'count': edges.loc[i, 'count'],
					'named': edges.loc[i, 'named'],
					'minimum': edges.loc[i, 'minimum']
				})
			drops.append(i)

edges.drop(index=drops, inplace=True)
edges = pd.concat([edges, pd.DataFrame(rows)], ignore_index=True)

kills.reset_index(inplace=True)
edges.reset_index(inplace=True)

### Replacing Character Names with Aliases

In [6]:
aliases['listed'] = aliases['character'].str.split(' / ')


for i in range(len(kills)):
	universe = kills['universe'][i]
	character = kills['character'][i]
	victim = kills['victims'][i]
	pool = aliases[aliases['universe'] == universe]
	pool.reset_index(inplace=True)

	for j in range(len(pool)):
		grouped = pool['listed'][j]
		if character in grouped:
			new = pool['character'][j]
			kills.at[i, 'character'] = new
		match = re.match(r'^(.*?)\s*\(([^()]*)\)$', character)
		if not match:
			match = ['', '', '']
		if match[1] in grouped and match[2] in worlds[worlds['universe'] == universe]['world'].values:
			new = pool['character'][j] + ' (' + match[2] + ')'
			kills.at[i, 'character'] = new

		if victim in grouped:
			new = pool['character'][j]
			kills.at[i, 'victims'] = new
		match = re.match(r'^(.*?)\s*\(([^()]*)\)$', victim)
		if not match:
			match = ['', '', '']
		if match[1] in grouped and match[2] in worlds[worlds['universe'] == universe]['world'].values:
			new = pool['character'][j] + ' (' + match[2] + ')'
			kills.at[i, 'victims'] = new


for i in range(len(deaths)):
	universe = deaths['universe'][i]
	character = deaths['character'][i]
	party = deaths['responsible party'][i]
	pool = aliases[aliases['universe'] == universe]
	pool.reset_index(inplace=True)

	for j in range(len(pool)):
		grouped = pool['listed'][j]
		if character in grouped:
			new = pool['character'][j]
			deaths.at[i, 'character'] = new
		match = re.match(r'^(.*?)\s*\(([^()]*)\)$', character)
		if not match:
			match = ['', '', '']
		if match[1] in grouped and match[2] in worlds[worlds['universe'] == universe]['world'].values:
			new = pool['character'][j] + ' (' + match[2] + ')'
			deaths.at[i, 'character'] = new

		changes = dict()
		for member in party:
			if member in grouped:
				new = pool['character'][j]
				changes[member] = new
			match = re.match(r'^(.*?)\s*\(([^()]*)\)$', member)
			if not match:
				match = ['', '', '']
			if match[1] in grouped and match[2] in worlds[worlds['universe'] == universe]['world'].values:
				new = pool['character'][j] + ' (' + match[2] + ')'
				changes[member] = new
		if changes:
			party = [changes.get(member, member) for member in party]
			deaths.at[i, 'responsible party'] = party


for i in range(len(edges)):
	universe = edges['universe'][i]
	killer = edges['killer'][i]
	victim = edges['victim'][i]
	pool = aliases[aliases['universe'] == universe]
	pool.reset_index(inplace=True)

	for j in range(len(pool)):
		grouped = pool['listed'][j]
		if killer in grouped:
			new = pool['character'][j]
			edges.at[i, 'killer'] = new
		match = re.match(r'^(.*?)\s*\(([^()]*)\)$', killer)
		if not match:
			match = ['', '', '']
		if match[1] in grouped and match[2] in worlds[worlds['universe'] == universe]['world'].values:
			new = pool['character'][j] + ' (' + match[2] + ')'
			edges.at[i, 'killer'] = new

		if victim in grouped:
			new = pool['character'][j]
			edges.at[i, 'victim'] = new
		match = re.match(r'^(.*?)\s*\(([^()]*)\)$', victim)
		if not match:
			match = ['', '', '']
		if match[1] in grouped and match[2] in worlds[worlds['universe'] == universe]['world'].values:
			new = pool['character'][j] + ' (' + match[2] + ')'
			edges.at[i, 'victim'] = new

### Checking for Character Versions

In [7]:
version_lookup = {}
for _, row in versions.iterrows():
	base = row['character']
	universe = row['universe']
	all_versions = [base] + [v.strip() for v in base.split(' / ')] + [v.strip() for v in row['versions'].split(' / ')]
	for version in all_versions:
		version_lookup.setdefault((universe, version), set()).add(base)


def world_versions(df):
	for _, row in df.iterrows():
		character = row['character']
		universe = row['universe']

		match = re.match(r'^(?P<base>.+?)\s*\((?P<world>.+?)\)$', character)
		if match:
			base = match.group('base').strip()
			world = match.group('world').strip()

			if ((worlds['universe'] == universe) & (worlds['world'] == world)).any():
				version_lookup.setdefault((universe, base), set()).add(base)
				splits = [v.strip() for v in character.split(' / ')]
				for split in splits:
					version_lookup.setdefault((universe, split), set()).add(base)


world_versions(kills)
world_versions(deaths)

version_lookup = {k: list(v) for k, v in version_lookup.items()}

def inject_versions(df):
	expanded = []
	for _, row in df.iterrows():
		expanded.append(row.to_dict())

		character = row['character']
		universe = row['universe']

		splat = character.split(' / ')[0]

		if (universe, splat) in version_lookup:
			for base in version_lookup[(universe, splat)]:
				agg = row.to_dict()
				agg['character'] = base + ' ⟨composite⟩'
				expanded.append(agg)

		if ("*", splat) in version_lookup:
			for base in version_lookup[("*", splat)]:
				agg = row.to_dict()
				agg['universe'] = '*'
				agg['character'] = base + ' ⟨composite⟩'
				expanded.append(agg)

	return pd.DataFrame(expanded)


kills = inject_versions(kills)
deaths = inject_versions(deaths)

### Analyzing and Organizing the Deaths

In [8]:
unnamed_pattern = re.compile(r"^<(\d+(?:[.,]\d+)*)(\+)?>\s*(.*)$")

def nunique_filtered(series):
	return series[~series.str.match(unnamed_pattern, na=False)].nunique()

In [9]:
death_display = deaths[[not x.endswith(' ⟨composite⟩') for x in deaths['character']]]
death_display['named_count'] = death_display['count'].where(death_display['named'], 0)
death_display = death_display.groupby(by=['universe']).aggregate(
	count = ('count', 'sum'),
	named_count = ('named_count', 'sum'),
	unique_count = ('character', nunique_filtered),
	minimum = ('minimum', 'any')
)

print('----- Deadliest Universes -----')
death_display.sort_values(by=['count'], ascending=False, inplace=True)
death_display['count'] = death_display.apply(lambda row: format_count(row['count'], row['minimum']), axis=1)
death_display['named_count'] = death_display.apply(lambda row: format_count(row['named_count'], row['minimum']), axis=1)
pd.DataFrame(death_display.drop(columns=['minimum']).reset_index().rename(columns={0:'deaths'}))

----- Deadliest Universes -----

                    universe          count    named_count  unique_count
0    A Certain Magical Index  301083119748+  300000010141+            93
1                    Déjà Vu  188350258942+          4780+            60
2         Mother of Learning   51794612222+        105252+           120
3                Zero Escape    6000000221+           206+            43
4          Science Adventure    5700000027+            27+             7
5            The Perfect Run    4024539690+       2010930+            89
6                  Nasuverse    1180239447+           426+           217
7                    Re Zero     100159743+     100014456+           142
8                 Code Geass      35000058+            58+            54
9            Hunter × Hunter       5663910+           150+           150
10           Attack on Titan       2837951+           139+           138
11            Kingdom Hearts        484727+           106+            81
12            Akame ga Kill!        400348+           148+           135
13              Project Moon        383315+           408+           238
14        Deadman Wonderland        148121+            53+            50
15            Jujutsu Kaisen          7788+            86+            72
16   The World Ends with You           6231             54            36
17             Hollow Knight           4962            158           130
18            Dragon's Dogma           3934             45            44
19               Tokyo Ghoul          2762+           140+           136
20               Danganronpa          2592+           178+           171
21               Blasphemous           1793             62            47
22            Monster Hunter           1668              0             0
23              Bloodstained           1167             72            60
24           The Evil Within           714+            57+            51
25                     Gantz           701+           121+            70
26              Clair Obscur           589+           250+           242
27                Dark Souls            529            249           209
28                Elden Ring            511            248           226
29         Slay the Princess           254+           254+             3
30             Final Fantasy            235             25            25
31                     Ozark            225             39            39
32          Assassin's Creed           217+            91+            90
33  Jojo's Bizarre Adventure            175            143           129
34                     Barry            145             47            47
35       Alice in Borderland            142             58            58
36           The Golden Idol            106             89            88
37                Watch Dogs             88             88            82
38       Lords of the Fallen             87             87            76
39                  Claymore             80             80            74
40         Little Nightmares             78             16            16
41              Golden Kamuy             77             77            77
42           Life is Strange             70             70            48
43   Return of the Obra Dinn             66             57            57
44                 Star Wars             56             56            56
45              Ace Attorney             50             50            50
46                 Code Vein             46             46            39
47              Future Diary             44             44            42
48                  Infamous             39             39            34
49        Mobile Suit Gundam             37             37            37
50      AI The Somnium Files             33             29            23
51                Just Cause             28             28            27
52               Tomb Raider             19             19            18
53                 Dr. Stone             19             18            18
54    Attorney of the Arcane             18             18            17
55            Staffer Series             15             15             8

In [10]:
print('----- Deadliest Universes for Named Characters -----')
death_display.sort_values(by=['named_count'], ascending=False, inplace=True)
pd.DataFrame(death_display.drop(columns=['minimum']).reset_index().rename(columns={0:'deaths'}))

----- Deadliest Universes for Named Characters -----

                    universe          count    named_count  unique_count
0           Assassin's Creed           217+            91+            90
1            The Golden Idol            106             89            88
2                 Watch Dogs             88             88            82
3        Lords of the Fallen             87             87            76
4             Jujutsu Kaisen          7788+            86+            72
5                   Claymore             80             80            74
6               Golden Kamuy             77             77            77
7               Bloodstained           1167             72            60
8            Life is Strange             70             70            48
9                Blasphemous           1793             62            47
10                Code Geass      35000058+            58+            54
11       Alice in Borderland            142             58            58
12           The Evil Within           714+            57+            51
13   Return of the Obra Dinn             66             57            57
14                 Star Wars             56             56            56
15   The World Ends with You           6231             54            36
16        Deadman Wonderland        148121+            53+            50
17              Ace Attorney             50             50            50
18                   Déjà Vu  188350258942+          4780+            60
19                     Barry            145             47            47
20                 Code Vein             46             46            39
21            Dragon's Dogma           3934             45            44
22              Future Diary             44             44            42
23                 Nasuverse    1180239447+           426+           217
24              Project Moon        383315+           408+           238
25                  Infamous             39             39            34
26                     Ozark            225             39            39
27        Mobile Suit Gundam             37             37            37
28   A Certain Magical Index  301083119748+  300000010141+            93
29      AI The Somnium Files             33             29            23
30                Just Cause             28             28            27
31         Science Adventure    5700000027+            27+             7
32         Slay the Princess           254+           254+             3
33              Clair Obscur           589+           250+           242
34             Final Fantasy            235             25            25
35                Dark Souls            529            249           209
36                Elden Ring            511            248           226
37               Zero Escape    6000000221+           206+            43
38           The Perfect Run    4024539690+       2010930+            89
39               Tomb Raider             19             19            18
40    Attorney of the Arcane             18             18            17
41                 Dr. Stone             19             18            18
42               Danganronpa          2592+           178+           171
43         Little Nightmares             78             16            16
44             Hollow Knight           4962            158           130
45           Hunter × Hunter       5663910+           150+           150
46            Staffer Series             15             15             8
47            Akame ga Kill!        400348+           148+           135
48  Jojo's Bizarre Adventure            175            143           129
49               Tokyo Ghoul          2762+           140+           136
50           Attack on Titan       2837951+           139+           138
51                     Gantz           701+           121+            70
52            Kingdom Hearts        484727+           106+            81
53        Mother of Learning   51794612222+        105252+           120
54                   Re Zero     100159743+     100014456+           142
55            Monster Hunter           1668              0             0

In [11]:
print('----- Deadliest Universes for Unique Characters -----')
death_display.sort_values(by=['unique_count'], ascending=False, inplace=True)
pd.DataFrame(death_display.drop(columns=['minimum']).reset_index().rename(columns={0:'deaths'}))

----- Deadliest Universes for Unique Characters -----

                    universe          count    named_count  unique_count
0               Clair Obscur           589+           250+           242
1               Project Moon        383315+           408+           238
2                 Elden Ring            511            248           226
3                  Nasuverse    1180239447+           426+           217
4                 Dark Souls            529            249           209
5                Danganronpa          2592+           178+           171
6            Hunter × Hunter       5663910+           150+           150
7                    Re Zero     100159743+     100014456+           142
8            Attack on Titan       2837951+           139+           138
9                Tokyo Ghoul          2762+           140+           136
10            Akame ga Kill!        400348+           148+           135
11             Hollow Knight           4962            158           130
12  Jojo's Bizarre Adventure            175            143           129
13        Mother of Learning   51794612222+        105252+           120
14   A Certain Magical Index  301083119748+  300000010141+            93
15          Assassin's Creed           217+            91+            90
16           The Perfect Run    4024539690+       2010930+            89
17           The Golden Idol            106             89            88
18                Watch Dogs             88             88            82
19            Kingdom Hearts        484727+           106+            81
20              Golden Kamuy             77             77            77
21       Lords of the Fallen             87             87            76
22                  Claymore             80             80            74
23            Jujutsu Kaisen          7788+            86+            72
24                     Gantz           701+           121+            70
25              Bloodstained           1167             72            60
26                   Déjà Vu  188350258942+          4780+            60
27       Alice in Borderland            142             58            58
28   Return of the Obra Dinn             66             57            57
29                 Star Wars             56             56            56
30                Code Geass      35000058+            58+            54
31           The Evil Within           714+            57+            51
32              Ace Attorney             50             50            50
33        Deadman Wonderland        148121+            53+            50
34           Life is Strange             70             70            48
35                     Barry            145             47            47
36               Blasphemous           1793             62            47
37            Dragon's Dogma           3934             45            44
38               Zero Escape    6000000221+           206+            43
39              Future Diary             44             44            42
40                     Ozark            225             39            39
41                 Code Vein             46             46            39
42        Mobile Suit Gundam             37             37            37
43   The World Ends with You           6231             54            36
44                  Infamous             39             39            34
45                Just Cause             28             28            27
46             Final Fantasy            235             25            25
47      AI The Somnium Files             33             29            23
48               Tomb Raider             19             19            18
49                 Dr. Stone             19             18            18
50    Attorney of the Arcane             18             18            17
51         Little Nightmares             78             16            16
52            Staffer Series             15             15             8
53         Science Adventure    5700000027+            27+             7
54         Slay the Princess           254+           254+             3
55            Monster Hunter           1668              0             0

In [12]:
def join_with_counts(series):
	seen = {}
	result = []
	for v in series:
		if v not in seen:
			seen[v] = 1
			result.append(v)
		else:
			seen[v] += 1
	return ", ".join(
		f"{v} (×{seen[v]})" if seen[v] > 1 else v
		for v in result
	)

In [13]:
kills['named_killed'] = kills['killed'].where(kills['named'], 0)

kills = kills.groupby(by=['universe', 'character']).aggregate(
	killed = ('killed', 'sum'),
	named_killed = ('named_killed', 'sum'),
	unique_killed = ('victims', nunique_filtered),
	victims = ('victims', join_with_counts),
	named = ('named', 'any'),
	minimum = ('minimum', 'any'),
	)

kills.reset_index(inplace=True)
kills_display = kills.drop('victims', axis=1).sort_values(by='killed', ascending=False).drop_duplicates('universe')
kills_display['killed'] = kills_display.apply(lambda row: format_count(row['killed'], row['minimum']), axis=1)
print('----- Deadliest Character Killer per Universe -----')
kills_display.drop(columns=['minimum']).reset_index(drop=True)

----- Deadliest Character Killer per Universe -----

,universe,character,killed,named_killed,unique_killed,named
0,A Certain Magical Index,Othinus,300000010033+,300000010033,1,True
1,Déjà Vu,Erebus / Embodiment of Darkness / Destroyer,176000253855+,4374,40,True
2,Mother of Learning,Panaxeth / He of the Flowing Flesh,51300105010+,105007,107,True
3,Zero Escape,Delta / Brother / Q / Zero II,6000000141+,141,19,True
4,The Perfect Run,Eva Fabre / Alchemist,2000000346+,6,6,True
5,Nasuverse,Camazotz ⟨composite⟩,1000000000+,0,0,False
6,Code Geass,Lelouch vi Britannia / Lelouch Lamperouge / Ju...,35000020+,20,19,True
7,Attack on Titan,Eren Jaeger ⟨composite⟩,2000126+,25,25,True
8,Hunter × Hunter,Meruem,538122,7,7,True
9,Kingdom Hearts,Xehanort / Young Xehanort ⟨composite⟩,432439+,22,20,True
10,Akame ga Kill!,Esdeath,400005+,5,5,True
11,Project Moon,Carmen,380344+,105,101,True
12,Deadman Wonderland,Shiro / Wretched Egg,148030+,12,11,True
13,Re Zero,Natsuki Subaru / Purge King ⟨composite⟩,127611+,89,44,True
14,The World Ends with You,Neku Sakuraba,6123,4,4,True
15,Jujutsu Kaisen,Yuta Okkotsu,4476+,7,6,True
16,Dragon's Dogma,The Arisen,3912,26,26,True
17,Hollow Knight,Hornet,2833,36,35,True
18,Danganronpa,Junko Enoshima / Ryoko Otonashi,2404+,27,27,True
19,Tokyo Ghoul,Itsuki Marude,2263+,1,1,True
20,Blasphemous,Penitent One,1769,38,34,True
21,Monster Hunter,Hunter (MHWI) / The Sapphire Star / The White ...,1665,0,0,False
22,Bloodstained,Miriam,1118,23,21,True
23,The Evil Within,Sebastian Castellanos,591,24,21,True
24,Elden Ring,The Tarnished,422,164,146,True
25,Gantz,Shion Izumi,376,8,8,True
26,Clair Obscur,Painted Verso,311,113,110,True
27,Final Fantasy,Lightning / Claire Farron,226,16,16,True
28,Slay the Princess,The Princess / The Shifting Mound / The Advers...,186+,186,3,True
29,Dark Souls,Chosen Undead,183,47,45,True
30,Assassin's Creed,Ezio Auditore da Firenze,103,40,40,True
31,Ozark,Darlene Snell,63,6,6,True
32,Life is Strange,Maxine Caulfield,46,46,40,True
33,Lords of the Fallen,The Lampbearer / The Deathless One,45,45,42,True
34,Barry,Barry Berkman,43,13,13,True
35,Alice in Borderland,Mira Kano,39,5,5,True
36,Star Wars,Cal Kestis,38,38,38,True
37,Code Vein,Louis Amamiya,28,28,27,True
38,Little Nightmares,Mono,27,3,3,True
39,Future Diary,Deus Ex Machina ⟨composite⟩,24,24,23,True
40,Jojo's Bizarre Adventure,Dio Brando,20,10,10,True
41,Watch Dogs,Aiden Pearce / The Vigilante / The Fox,19,19,19,True
42,Infamous,Cole MacGrath ⟨composite⟩,19,19,17,True
43,AI The Somnium Files,Saito Sejima / New Cyclops Killer,17,13,10,True
44,Claymore,Isley,17,17,17,True
45,Return of the Obra Dinn,Kraken,16,16,16,True
46,The Golden Idol,Lavu Mata,15,2,2,True
47,Golden Kamuy,Hyakunosuke Ogata,12,12,12,True
48,Mobile Suit Gundam,Mikazuki Augus / The Devil of Tekkadan,12,12,12,True
49,Science Adventure,Yuugo Tennouji / Ferdinand Braun / FB,10,10,3,True
50,Just Cause,Rico Rodriguez,9,9,9,True
51,Tomb Raider,Lara Croft,7,7,7,True
52,Dr. Stone,Hyoga Akatsuki,7,7,7,True
53,Attorney of the Arcane,Eris Illmater / The Empress of Discord / The L...,6,6,6,True
54,Staffer Series,Pandoria Redfins / Investigator,5,5,2,True
55,Ace Attorney,Joe Darke,5,5,5,True

In [14]:
kills_display = kills.drop('victims', axis=1).sort_values(by='named_killed', ascending=False).drop_duplicates('universe')
kills_display['named_killed'] = kills_display.apply(lambda row: format_count(row['named_killed'], row['minimum']), axis=1)
print('----- Deadliest Named Character Killer per Universe -----')
kills_display.drop(columns=['minimum']).reset_index(drop=True)

----- Deadliest Named Character Killer per Universe -----

,universe,character,killed,named_killed,unique_killed,named
0,A Certain Magical Index,Othinus,300000010033,300000010033+,1,True
1,The Perfect Run,Leonard Hargraves / Living Sun / Sunshine,4500368,2000368+,5,True
2,Mother of Learning,Panaxeth / He of the Flowing Flesh,51300105010,105007+,107,True
3,Re Zero,Reinhard van Astrea ⟨composite⟩,10036,10016+,17,True
4,Déjà Vu,Erebus / Embodiment of Darkness / Destroyer,176000253855,4374+,40,True
5,Slay the Princess,The Princess / The Shifting Mound / The Advers...,186,186+,3,True
6,Elden Ring,The Tarnished,422,164,146,True
7,Zero Escape,Delta / Brother / Q / Zero II,6000000141,141+,19,True
8,Nasuverse,Ritsuka Fujimaru,1904,126,63,True
9,Project Moon,Roland / The Black Silence,357,118,113,True
10,Clair Obscur,Painted Verso,311,113,110,True
11,Dark Souls,Bearer of the Curse,164,96,86,True
12,Kingdom Hearts,Sora ⟨composite⟩,36824,51+,37,True
13,Life is Strange,Maxine Caulfield,46,46,40,True
14,Lords of the Fallen,The Lampbearer / The Deathless One,45,45,42,True
15,Hollow Knight,The Knight / Lord of Shades,2050,43,33,True
16,Assassin's Creed,Ezio Auditore da Firenze,103,40,40,True
17,Akame ga Kill!,Akame,40,40,40,True
18,Blasphemous,Penitent One,1769,38,34,True
19,Star Wars,Cal Kestis,38,38,38,True
20,Danganronpa,Monokuma,38,38,36,True
21,Bloodstained,Gebel,35,35,35,True
22,Code Vein,Louis Amamiya,28,28,27,True
23,Dragon's Dogma,The Arisen,3912,26,26,True
24,Attack on Titan,Eren Jaeger ⟨composite⟩,2000126,25+,25,True
25,Hunter × Hunter,Genthru,25,25,25,True
26,The Evil Within,Sebastian Castellanos,591,24,21,True
27,Future Diary,Deus Ex Machina ⟨composite⟩,24,24,23,True
28,Code Geass,Lelouch vi Britannia / Lelouch Lamperouge / Ju...,35000020,20+,19,True
29,Jojo's Bizarre Adventure,Yoshikage Kira,19,19,18,True
30,Infamous,Cole MacGrath ⟨composite⟩,19,19,17,True
31,Watch Dogs,Aiden Pearce / The Vigilante / The Fox,19,19,19,True
32,Claymore,Isley,17,17,17,True
33,Return of the Obra Dinn,Kraken,16,16,16,True
34,Final Fantasy,Lightning / Claire Farron,226,16,16,True
35,Gantz,Gantz,223,15+,15,True
36,Alice in Borderland,Enji Matsushita,18,15,15,True
37,Jujutsu Kaisen,Sukuna / Ryomen Sukuna,17,13+,13,True
38,Barry,Barry Berkman,43,13,13,True
39,AI The Somnium Files,Saito Sejima / New Cyclops Killer,17,13,10,True
40,Deadman Wonderland,Shiro / Wretched Egg,148030,12+,11,True
41,Mobile Suit Gundam,Mikazuki Augus / The Devil of Tekkadan,12,12,12,True
42,Golden Kamuy,Hyakunosuke Ogata,12,12,12,True
43,The Golden Idol,Jack Nowak / Hunter Wolf,11,11,10,True
44,Science Adventure,Yuugo Tennouji / Ferdinand Braun / FB,10,10,3,True
45,The World Ends with You,Shiba Miyakaze,10,10,10,True
46,Just Cause,Rico Rodriguez,9,9,9,True
47,Tokyo Ghoul,Seidou Takizawa / Owl,13,7,7,True
48,Tomb Raider,Lara Croft,7,7,7,True
49,Dr. Stone,Hyoga Akatsuki,7,7,7,True
50,Ozark,Nelson,7,7,7,True
51,Attorney of the Arcane,Eris Illmater / The Empress of Discord / The L...,6,6,6,True
52,Ace Attorney,Joe Darke,5,5,5,True
53,Staffer Series,Pandoria Redfins / Investigator,5,5,2,True
54,Little Nightmares,Six,18,5,5,True
55,Monster Hunter,Seliana Melder,36,0,0,False

In [15]:
kills_display = kills.drop('victims', axis=1).sort_values(by='unique_killed', ascending=False).drop_duplicates('universe')
kills_display['unique_killed'] = kills_display.apply(lambda row: format_count(row['unique_killed'], row['minimum']), axis=1)
print('----- Deadliest Unique Character Killer per Universe -----')
kills_display.drop(columns=['minimum']).reset_index(drop=True)

----- Deadliest Unique Character Killer per Universe -----

,universe,character,killed,named_killed,unique_killed,named
0,Elden Ring,The Tarnished,422,164,146,True
1,Project Moon,Roland / The Black Silence,357,118,113,True
2,Clair Obscur,Verso Dessendre ⟨composite⟩,311,113,110,True
3,Mother of Learning,Panaxeth / He of the Flowing Flesh,51300105010,105007,107+,True
4,Dark Souls,Bearer of the Curse,164,96,86,True
5,Nasuverse,Ritsuka Fujimaru,1904,126,63,True
6,The Perfect Run,Ryan Romano / Quicksave / Riri / Clockstopper,10002776,503,47+,True
7,Re Zero,Natsuki Subaru / Purge King ⟨composite⟩,127611,89,44+,True
8,Lords of the Fallen,The Lampbearer / The Deathless One,45,45,42,True
9,Life is Strange,Maxine Caulfield,46,46,40,True
10,Déjà Vu,Erebus / Embodiment of Darkness / Destroyer,176000253855,4374,40+,True
11,Akame ga Kill!,Akame,40,40,40,True
12,Assassin's Creed,Ezio Auditore da Firenze,103,40,40,True
13,Star Wars,Cal Kestis,38,38,38,True
14,Kingdom Hearts,Sora ⟨composite⟩,36824,51,37+,True
15,Danganronpa,Monokuma,38,38,36,True
16,Hollow Knight,Hornet,2833,36,35,True
17,Bloodstained,Gebel,35,35,35,True
18,Blasphemous,Penitent One,1769,38,34,True
19,Code Vein,Louis Amamiya,28,28,27,True
20,Dragon's Dogma,The Arisen,3912,26,26,True
21,Attack on Titan,Eren Jaeger ⟨composite⟩,2000126,25,25+,True
22,Hunter × Hunter,Genthru,25,25,25,True
23,Future Diary,Deus Ex Machina ⟨composite⟩,24,24,23,True
24,The Evil Within,Sebastian Castellanos,591,24,21,True
25,Zero Escape,Delta / Brother / Q / Zero II,6000000141,141,19+,True
26,Code Geass,Lelouch vi Britannia / Lelouch Lamperouge / Ju...,35000020,20,19+,True
27,Watch Dogs,Aiden Pearce / The Vigilante / The Fox,19,19,19,True
28,Jojo's Bizarre Adventure,Yoshikage Kira,19,19,18,True
29,Claymore,Isley,17,17,17,True
30,Infamous,Cole MacGrath ⟨composite⟩,19,19,17,True
31,Return of the Obra Dinn,Kraken,16,16,16,True
32,Final Fantasy,Lightning / Claire Farron,226,16,16,True
33,Gantz,Gantz,223,15,15+,True
34,Alice in Borderland,Enji Matsushita,18,15,15,True
35,A Certain Magical Index,Accelerator,10043,15,14,True
36,Barry,Barry Berkman,43,13,13,True
37,Jujutsu Kaisen,Sukuna / Ryomen Sukuna,17,13,13+,True
38,Golden Kamuy,Hyakunosuke Ogata,12,12,12,True
39,Mobile Suit Gundam,Mikazuki Augus / The Devil of Tekkadan,12,12,12,True
40,Deadman Wonderland,Shiro / Wretched Egg,148030,12,11+,True
41,The World Ends with You,Shiba Miyakaze,10,10,10,True
42,AI The Somnium Files,Saito Sejima / New Cyclops Killer,17,13,10,True
43,The Golden Idol,Jack Nowak / Hunter Wolf,11,11,10,True
44,Just Cause,Rico Rodriguez,9,9,9,True
45,Tokyo Ghoul,Seidou Takizawa / Owl,13,7,7,True
46,Tomb Raider,Lara Croft,7,7,7,True
47,Dr. Stone,Hyoga Akatsuki,7,7,7,True
48,Ozark,Nelson,7,7,7,True
49,Attorney of the Arcane,Eris Illmater / The Empress of Discord / The L...,6,6,6,True
50,Little Nightmares,Six,18,5,5,True
51,Ace Attorney,Mael Stronghart,5,5,5,True
52,Science Adventure,Yuugo Tennouji / Ferdinand Braun / FB,10,10,3,True
53,Slay the Princess,The Princess / The Shifting Mound / The Advers...,186,186,3+,True
54,Staffer Series,Pandoria Redfins / Investigator,5,5,2,True
55,Monster Hunter,Third Fleet Senior Scholar,1,0,0,False

In [16]:
deaths['character'] = deaths['character'].apply(lambda x: x if isinstance(x, list) else [x])
deaths_exploded = deaths.explode('character', ignore_index=True)
deaths_exploded = deaths_exploded[deaths_exploded['named'] == True]
deaths_count = deaths_exploded.groupby(['universe', 'character']).aggregate({'count': sum}).reset_index()
deaths_count.rename(columns={'count': 'deaths'}, inplace=True)

kills_count = kills.copy()
kills_count.drop(['victims'], axis=1, inplace=True)
kills_count.columns = ['universe', 'character', 'killed', 'named_killed', 'unique_killed', 'named', 'minimum']

summary = pd.merge(deaths_count, kills_count, left_on=['universe', 'character'], right_on=['universe', 'character'], how='outer')
summary.fillna(0, inplace=True)
summary.sort_values(by=['universe', 'character'], inplace=True)

summary = summary.round(decimals=2).astype(object)
summary = summary.astype(str)
summary = summary.replace(to_replace = "\.0+$",value = "", regex = True)

In [17]:
deaths['resulting status'] = ''

for i in range(len(deaths)):
	if deaths.loc[i, 'character'][0].endswith(' ⟨composite⟩'):
		composite = True
	else:
		composite = False

	type = str(deaths['type'][i]).split(' | ')

	conditions = ["determinant", "continuant"]
	if re.search('|'.join(conditions), str(type)):
		dependent = True
	else:
		dependent = False

	conditions = ["unavoidable"]
	if re.search('|'.join(conditions), str(type)):
		dependent = False

	conditions = ["revived", "reincarnated", "undone", "non-canon", "clone", "alternate"]
	if re.search('|'.join(conditions), str(type)):
		alive = True
	else:
		alive = False

	conditions = ["physical", "brain-dead", "undead"]
	if re.search('|'.join(conditions), str(type)):
		extant = True
	else:
		extant = False

	if composite:
		deaths['resulting status'][i] = 'composite'
	elif alive:
		deaths['resulting status'][i] = 'alive'
	elif extant and not alive:
		deaths['resulting status'][i] = 'extant'
	elif dependent and not extant and not alive:
		deaths['resulting status'][i] = 'dependent'
	elif not dependent and not extant and not alive:
		deaths['resulting status'][i] = 'deceased'

In [18]:
priority = {"composite": 0, "deceased": 1, "extant": 2, "dependent": 3, "alive": 4}

status = deaths.copy()
status["character"] = status["character"].apply(lambda x: x if isinstance(x, list) else [x])
status = status.explode("character", ignore_index=True)

status["priority"] = status["resulting status"].map(priority)

status = status.loc[status.groupby(["universe", "character"])["priority"].idxmin()]
status = status.drop(columns=["priority", "responsible party", "death", "type"]).reset_index(drop=True)
status.rename(columns={"resulting status": "last known status"}, inplace=True)

summary = pd.merge(summary, status, on=["universe", "character"], how="outer")
summary["last known status"] = summary["last known status"].fillna("alive")

### Generating the README file

In [19]:
progress = """### Terminology for Character Statuses

- **deceased** - the character stayed dead.
- **alive** - the character did not die or did not stay dead.
- - **revived**      - this death was nullified when the character was brought back from the dead.
- - **reincarnated** - this death was nullified when the character was reborn with their memories.
- - **undone**       - this death was nullified via time travel.
- - **non-canon**    - this death happened, but is not considered canon when it comes to the character's status.
- - **clone**        - this death happened to a clone or copy of a character.
- - **alternate**    - this death happened to a different version of the character, usually within an alternate universe.
- **dependent** - the character may or may not be deceased depending on certain factors.
- - **determinant** - this death happening depends upon a player's choice.
- - **continuant**  - this death exists but not in every adaptation of a story, and the character's canonical status is unspecified.
- - **unavoidable** - this death happens differently depending upon a choice but always happens nonetheless.
- **extant** - the character is arguably deceased yet still remains due to specific circumstances.
- - **physical**   - this death concerns only a character's body, leaving their mind or soul alive.
- - **brain-dead** - this death left the character only physically alive, with no brain activity possible.
- - **undead**     - this death turned the character into an undead being such as a zombie or a ghost.
- **composite** - the 'character' refers here to a cumulative summary of all different versions of a character.


### Status of Incomplete Entries

- Gantz - up to and including the **Dinosaur Alien Mission Arc**
- Hunter × Hunter - up to and including the **13th Hunter Chairman Election Arc**


### Summary of Universes and Entries

"""

with open('README.md', 'w+') as f:
	f.write(progress)

In [20]:
deaths_summary = deaths.copy()
deaths_summary.rename(columns={'count': 'deaths'}, inplace=True)
deaths_summary.loc[[x[0].endswith(' ⟨composite⟩') for x in deaths_summary['character']], 'deaths'] = 0
deaths_summary = deaths_summary[deaths_summary['universe'] != '*']
deaths_summary = deaths_summary.drop(["responsible party", "death", "type", "resulting status"], axis=1)

deaths_summary['character'] = deaths_summary['character'].str[0]
deaths_summary['named_deaths'] = deaths_summary['deaths'].where(deaths_summary['named'], 0)
deaths_summary = deaths_summary.groupby(["universe", "entry"]).aggregate(
	deaths = ("deaths", 'sum'),
	named_deaths = ('named_deaths', 'sum'),
	unique_deaths = ('character', nunique_filtered)
)

deaths_summary = deaths_summary.reset_index()

final_rows = []
final_output = deaths_summary.copy()

grand_total = deaths_summary["deaths"].sum()
grand_total_named = deaths_summary["named_deaths"].sum()
grand_total_unique = deaths_summary["unique_deaths"].sum()

final_rows.append({
	"universe": "**\***",
	"entry": "**\***",
	"deaths": grand_total,
	"named_deaths": grand_total_named,
	"unique_deaths": grand_total_unique,
})
final_output.loc[len(final_output)] = ['*', '*', grand_total, grand_total_named, grand_total_unique]

for universe, group in deaths_summary.groupby("universe"):
	universe_total = group["deaths"].sum()
	universe_total_named = group["named_deaths"].sum()
	universe_total_unique = group["unique_deaths"].sum()

	final_rows.append({
		"universe": f"**{universe}**",
		"entry": "**\***",
		"deaths": universe_total,
		"named_deaths": universe_total_named,
		"unique_deaths": universe_total_unique,
	})
	final_output.loc[len(final_output)] = [universe, '*', universe_total, universe_total_named, universe_total_unique]

	final_rows.extend(group.to_dict(orient='records'))

final_table = pd.DataFrame(final_rows)

mask = final_table["universe"].str.startswith("**")

final_table["deaths"] = pd.to_numeric(final_table["deaths"]).map("{:,}".format)
final_table.loc[mask, "deaths"] = "**" + final_table.loc[mask, "deaths"] + "**"

final_table["named_deaths"] = pd.to_numeric(final_table["named_deaths"]).map("{:,}".format)
final_table.loc[mask, "named_deaths"] = "**" + final_table.loc[mask, "named_deaths"] + "**"

final_table["unique_deaths"] = pd.to_numeric(final_table["unique_deaths"]).map("{:,}".format)
final_table.loc[mask, "unique_deaths"] = "**" + final_table.loc[mask, "unique_deaths"] + "**"

deaths_table = final_table.to_markdown(tablefmt='github', index=False)

with open('README.md', 'a+') as f:
	f.write(deaths_table)

### Visualizing Death Links using PyVis

In [21]:
status = summary.copy()
status.drop(columns=["deaths", "killed"], inplace=True)
status.rename(columns={"last known status": "color"}, inplace=True)

colors = {"composite" : "#f0f0f0",
		  "alive" : "#107a06",
		  "extant" : "#0990b5",
		  "dependent" : "#631da3",
		  "deceased" : "#730a1c"}

status["color"].replace(colors, inplace=True)
status["character"] += " [" + status["universe"] + "]"

In [22]:
edges['killer'] += " [" + edges['universe'] + "]"
edges.loc[edges['killer'].str.startswith(' ['), 'killer'] = ''
edges['victim'] += " [" + edges['universe'] + "]"

nodes = pd.DataFrame()
nodes['character'] = pd.concat([edges.loc[edges["named"], "victim"], edges['killer']]).drop_duplicates().sort_values().reset_index(drop=True)

nodes = pd.merge(nodes, status, left_on='character', right_on='character', how='left')
nodes.sort_values(by=['character', 'color'], inplace=True)

deaths["character"] = deaths["character"].apply(lambda x: x if isinstance(x, list) else [x])
deaths = deaths.explode("character", ignore_index=True)

descriptions = deaths.groupby(by=['universe', 'character']).aggregate({'death':'\n'.join})
descriptions.reset_index(inplace=True)
descriptions['character'] += " [" + descriptions['universe'] + "]"
descriptions.drop(columns=['universe'], inplace=True)

nodes = pd.merge(nodes, descriptions, left_on=['character'], right_on=['character'], how='left')

profiles = pd.DataFrame(columns=['universe', 'character', 'profile'])

In [23]:
def make_network(universe):
	if universe == '*':
		return

	net = Network(height="100vh", width="100%", bgcolor="#111111", directed=True, notebook=False)
	net.force_atlas_2based(overlap=1, damping=0.5)

	current_edges = edges[edges['universe'] == universe]
	draw_edges = current_edges[current_edges['named']].copy()
	current_nodes = nodes[nodes['character'].str.endswith('[' + universe + ']')]

	killer_total = (current_edges.groupby("killer")["count"].sum().to_dict())
	killer_unnamed = (current_edges[~current_edges["named"]].groupby("killer")["count"].sum().to_dict())

	sources, targets = draw_edges['killer'], draw_edges['victim']
	description = draw_edges['death']
	edge_data = zip(sources, targets, description)

	for i in range(len(current_nodes)):
		victim = current_nodes.iloc[i]['character']
		color = current_nodes.iloc[i]['color']
		label = victim.split(" [")[0]
		description = current_nodes.iloc[i]['death']
		title = label + "\n\nCharacter Profile :" + "\n\n\n"

		if description == description:
			value = description.count('\n') + 1
			if value != 1:
				plural = 's'
			else:
				plural = ''

			title += str(value) + " Death" + plural + " :\n\n" + description + "\n\n"
		else:
			title += ''

		if victim != '':
			font = f"15px baskerville {color} sans-serif"
			net.add_node(victim, label=label, title=title, color=color, font=font)

	for src, dst, des in edge_data:
		if src != '':
			net.add_edge(src, dst, title=des, color='#e8ac87', width=1, dashes=False)

	neighbor_map = net.get_adj_list()

	pair_counts = (draw_edges.groupby(["killer", "victim"])["count"].sum().to_dict())

	def format_neighbors_with_counts(node_id):
		raw = neighbor_map.get(node_id, [])
		seen = []
		for nbr in raw:
			if nbr not in seen:
				seen.append(nbr)

		formatted = []
		for nbr in seen:
			cnt = int(pair_counts.get((node_id, nbr), 1))
			formatted.append(f"{nbr} (×{cnt})" if cnt > 1 else nbr)

		return "\n".join(sorted(formatted))


	for node in net.nodes:
		nid = node['id']

		named_neighbors = neighbor_map.get(nid, [])
		unique_named = len(named_neighbors)

		total_victims = int(killer_total.get(nid, 0))
		unnamed_victims = int(killer_unnamed.get(nid, 0))

		if unique_named:
			plural = 's' if unique_named != 1 else ''
			node['title'] += f"{unique_named} Named Victim{plural} :\n\n"
			node['title'] += format_neighbors_with_counts(nid)
			node['title'] = re.sub(r' \[.*?\]', '', node['title'])

		if unnamed_victims:
			node["title"] += f"\n\n + {unnamed_victims} Unnamed Victims"

		node['value'] = max(total_victims, 1)

	net.inherit_edge_colors(False)
	net.set_edge_smooth('dynamic')

	net.save_graph('Networks/' + universe + '.html')

	for node in net.nodes:
		universe = node['id'].split(' [')[1].split(']')[0]
		character = node['id'].split(' [')[0]
		profile = node['title']
		row = [universe, character, profile]
		profiles.loc[len(profiles)] = row

In [24]:
for universe in kills['universe'].unique():
	make_network(universe)

### Exports

In [25]:
deaths = deaths[deaths['named']]
deaths.drop(columns=['named', 'minimum'], inplace=True)

mapping = {
	"True": True,
	"False": False,
	"0": False,
}

summary["named"] = (
	summary["named_x"].replace(mapping).fillna(False).astype(bool) | summary["named_y"].fillna(False).astype(bool)
)
summary.loc[summary['named'].isna(), 'named'] = True
summary = summary[summary['named']]
summary.drop(columns=['count', 'named', 'named_x', 'named_y', 'minimum_x', 'minimum_y'], inplace=True)

final_output.sort_values(by=['universe', 'entry'], inplace=True)

deaths.to_csv('deaths.tsv', sep='\t', index=False)
kills.to_csv('kills.tsv', sep='\t', index=False)
summary.to_csv('summary.tsv', sep='\t', index=False)
final_output.to_csv('universes.tsv', sep='\t', index=False)